services:
  - type: web
    name: file-converter
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHONUNBUFFERED
        value: true